---
title: "Abstract for JSM"
output: html_document
---

# Abstract
Missing data is ubiquitous in data analysis. ggplot2, an implementation of the grammar of graphics is an incredibly popular way to produce data visualisations does not currently support missing data [@wickham2009ggplot2]. Principles of tidy data [@Wickham2014] states that each row is an observation and each column is a variable, which makes it easy and consistent to perform data manipulation and wrangling. However, there are currently no guidelines for representing additional missing data structures in a tidy format. This paper describes approaches for exploring missing data structure with minimal deviation from the common workflows of ggplot and tidy data structures. In this paper we describe typical sources of missing data, existing software for handling missing data, data structures for missing data, visulisations and numerical summaries for missing data, and then discuss the impact of these methods, the current limitations, and future plans.