---
title: "JSM Abstract Submission"
author: "Nicholas Tierney"
date: "27/01/2017"
output: html_document
bibliography: jsm2017.bib
---

## Session Type: Contributed

## Session Subtype: Paper

## Primary Sponsor: (Statistical Graphics).

### Data structures and functions for consistent exploration of missing data

Many real world data sets include missing values and these need to be carefully explored and
handled in the initial stages of analysis to avoid bias. However, exploring
why and how values are missing is typically an inefficient process. For
example, visualisation of data with missing values in R's base graphics silently drops missing values, and
ggplot2 typically results in a warning (Wickham, 2016). Additionally, missing data which have been imputed
are not typically distinguished in visualisation and summaries of data. Tidy data
structures as described in Wickham (2014), provide an efficient, easy
and consistent approach to performing data manipulation and wrangling 
where each row is an observation and each column is a variable. There are
currently no guidelines for representing missing data structures in a tidy
format, nor simple approaches to visualising missing values. This paper describes
an R package, `naniar`, for exploring missing values in data with minimal
deviation from the common workflows of ggplot and tidy data. Our package builds
data structures and functions that ensure missing values are handled effectively for
plotting and summarising data with missing values, and examining the effect of imputation.

**Bibliography**

Wickham, H. (2016). ggplot2: elegant graphics for data analysis. Springer.
Wickham, H. (2014). Tidy data. Journal of Statistical Software, 59(10), 1-23.

**Keywords**

- Missing Data
- Exploratory Data analysis
- Imputation
- Data Visualization
- Data Mining
- Statistical Graphics


Presenting author and co-author contact information:

**Presenting Author**: Nicholas Tierney (nicholas.tierney@gmail.com)
**Co-Authors**: Dianne Cook (dicook@monash.edu), Miles McBain (milesmcbain@gmail.com)
